build:
  cuda_version: "12.1.1"
  python_packages:
    - "accelerate==1.10.0"
    - "pydantic==2.11.7"
    - "transformers==4.55.2"
    - "torch==2.8.0"
    - "hf_transfer==0.1.9"
    - "huggingface-hub==0.34.4"
    - "inferless==0.2.15"
  run:
    - "pip install git+https://github.com/huggingface/diffusers"
