build:
  cuda_version: "12.1.1"
  python_packages:
    - "sentencepiece==0.2.0"
    - "pydantic==2.11.7"
    - "protobuf==6.31.1"
    - "transformers==4.55.0"
    - "diffusers==0.34.0"
    - "hf_transfer==0.1.9"
    - "huggingface-hub==0.34.4"
    - "inferless==0.2.15"
    - "torch==2.7.1"
